language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gatsby-cli
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run deploy
  on:
    branch: develop
